version:  2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages

  build_docker_image:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker Image
          command: |
            docker build -t jeyadevi/nodejswebapp1:latest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push jeyadevi/nodejswebapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
