version: 2.1

jobs:
  build:
    docker:
      - image: circleci/classic:latest  # Choose an executor with necessary tools pre-installed

    steps:
      - checkout

      # Install Docker
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo systemctl start docker
            sudo systemctl enable docker

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t nodejswebapp1 -t jeyadevikj/nodejswebapp1:latest .

      # Log in to Docker registry and push Docker image
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push jeyadevikj/nodejswebapp1:latest
