---
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/openjdk:11-jdk  # Choose an executor with Docker pre-installed

jobs:
  build:
    executor: my-executor
    steps:
      - checkout  # Example step to check out your code
      - run:
          name: Check Docker version
          command: docker --version
